<a href="https://colab.research.google.com/github/HIDDENDEN/Math_models/blob/main/MyWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing template ...


In [ ]:
# !cp "drive/My Drive/Science_res/TestClass.py" .
# import TestClass


In [ ]:
# test = TestClass.Vehicle(1,1,1)

In [ ]:
# print(test.brake())

import my classes

In [ ]:
!cp "drive/My Drive/Science_res/At.py" .
import At

!cp "drive/My Drive/Science_res/Fiu.py" .
import Fiu

!cp "drive/My Drive/Science_res/Alphax.py" .
import Alphax

!cp "drive/My Drive/Science_res/Kcit.py" .
import Kcit


initialize functions

In [ ]:
a_t = At.A_t()
kci_t = Kcit.Kci_t()
fi_u = Fiu.Fi_t()
alpha_x = Alphax.Alpha_x()

Import needed libs

In [37]:
import numpy as np
np.set_printoptions(linewidth=np.inf)# no extra newlines in output

import math


Set steps size of X axys and T axys


And *x_0* , *t_0*

In [ ]:
# Test L = 1 and T = 1
# Test num_of_steps N_x = 10 , N_t = 10
L = 1
T = 1
N_x = 10
N_t = 10

h_x = L/N_x
h_t = T/N_t

#Test segment 0 <= x <= 1
#Test segment 0 <= t <= 1

x_0 = 0
t_0 = 0

# **Method 1**

**Initialize two dim matrix for data storage**

In [ ]:
matrix = np.zeros((N_x + 1,N_t + 1))

**Filling matrix with border conditions**

In [ ]:
# First row filled with alpha(x_j)
for j in range(0, N_x+1):
  matrix[0][j] = alpha_x.compute(x_0 + h_x*j)

# First colomn filled with kci(t_i)
for i in range(0, N_t+1):
  matrix[i][0] = kci_t.compute(t_0 + h_t*i)

print(matrix)

[[0.  1.9 1.8 1.7 1.6 1.5 1.4 1.3 1.2 1.1 1. ]
 [0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.4 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.6 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.7 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.8 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.9 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]


*Define function for matrix computing*

In [ ]:
# def calculate_node(i,j,const_steps,x_i,t_j,matrix):
  # return (const_steps * (matrix[i][j-1]/h_t + matrix[i-1][j]/h_x - a_t.compute(t_j-h_t)*fi_u.compute(matrix[i-1][j-1]) ) )
def calculate_node(i, j, h_x, h_t, x_i, t_j, matrix):
  return (h_t * ( ( 1/h_x )*matrix[i-1][j] - (1/h_x - 1/h_t)*matrix[i][j] - a_t.compute(t_j)*fi_u.compute(matrix[i][j]) ) )


**Compute whole matrix**

In [ ]:
# Let 1/((1/h_t) + (1/h_x)) be written as const_steps
# const_steps = 1/(1/h_t + 1/h_x)

for i in range(0, (N_t - 1) + 1):   # t defines rows
  for j in range(1, (N_x) + 1):     # x defines colomns
    matrix[i+1][j] = round( calculate_node(i,j, h_x, h_t, x_0+h_x*j, t_0 + h_t*i,matrix) ,3) # round 3 digits after comma

print(matrix)

[[ 0.     1.9    1.8    1.7    1.6    1.5    1.4    1.3    1.2    1.1    1.   ]
 [ 0.1   -0.19  -0.18  -0.17  -0.16  -0.15  -0.14  -0.13  -0.12  -0.11  -0.1  ]
 [ 0.2    1.919  1.818  1.717  1.616  1.515  1.414  1.313  1.212  1.111  1.01 ]
 [ 0.3   -0.382 -0.362 -0.342 -0.322 -0.302 -0.281 -0.261 -0.241 -0.221 -0.201]
 [ 0.4    1.957  1.854  1.751  1.648  1.545  1.442  1.339  1.236  1.133  1.03 ]
 [ 0.5   -0.578 -0.547 -0.517 -0.487 -0.456 -0.425 -0.395 -0.365 -0.334 -0.304]
 [ 0.6    2.015  1.909  1.803  1.697  1.591  1.485  1.378  1.272  1.166  1.06 ]
 [ 0.7   -0.78  -0.738 -0.697 -0.657 -0.615 -0.574 -0.533 -0.492 -0.451 -0.41 ]
 [ 0.8    2.093  1.983  1.873  1.763  1.652  1.542  1.431  1.321  1.211  1.101]
 [ 0.9   -0.989 -0.936 -0.884 -0.833 -0.78  -0.728 -0.676 -0.624 -0.572 -0.52 ]
 [ 1.     2.192  2.077  1.961  1.846  1.73   1.615  1.499  1.383  1.268  1.153]]


In [ ]:
# print((matrix[:][1]))
# print((matrix[:][1])[3])

**Drawing section**

In [ ]:
# We'll draw using matplot lib
# importing the library 
import matplotlib.pyplot as plt  


*Drawing for U(x, t_const)*

In [ ]:
#data to be plotted
x = np.arange(x_0, x_0 + (N_x + 1)*h_x, h_x)

#set starting iteration ( i ) for t_i
#(selecting rows)
startIterationFor_t_i = 0
#set what num of first from t_i you want to display
num_of_graphs_rows = 5

for startIterationFor_t_i in range(num_of_graphs_rows):
  u = matrix[startIterationFor_t_i]
  #plotting
  plt.title("U(x, t_"+str(startIterationFor_t_i)+")")
  plt.xlabel("X axis")
  plt.ylabel("U(x, t_" +str(startIterationFor_t_i)+") axis")
  #show all x values
  plt.xticks(x)
  #set y axis fixed size
  axes = plt.axes()
  # axes.set_ylim([0, 4])
  #draw
  plt.plot(x,u, linestyle='--', marker='o', color = "red")
  plt.show()



*Drawing for U(x_const, t)*

In [ ]:
#data to be plotted
t = np.arange(t_0, t_0 + (N_t + 1)*h_t, h_t)

#set starting iteration ( j ) for x_j
#(selecting colomns)
startIterationFor_x_j = 0
#set what num of first from x_j you want to display
num_of_graphs_coloms = 5


for startIterationFor_x_j in range(num_of_graphs_coloms):
  u = matrix[:][startIterationFor_x_j]
  #plotting
  plt.title("U(x_"+str(startIterationFor_x_j)+", t)")
  plt.xlabel("T axis")
  plt.ylabel("U(x_" +str(startIterationFor_x_j)+", t) axis")
  #show all x values
  plt.xticks(t)
  #set y axis fixed size
  axes = plt.axes()
  # axes.set_ylim([0, 4])
  #draw
  plt.plot(x,u, linestyle='--', marker='o', color = "blue")
  plt.show()

# **#3rd Method**

**initialize two dim matrix for data storage on previous and current steps**

In [ ]:
from copy import copy, deepcopy

In [ ]:
matrix_prev = np.zeros((N_x + 1,N_t + 1))
matrix_prev = deepcopy(matrix)

matrix_cur = np.zeros((N_x + 1,N_t + 1))

Calculate integral (for method 3)
---
from a to b (f(x) dx)



In [ ]:
#calculate integral on simple segment
def integral_on_simple_segment(c,d,h, f, x_i,t_j):
  middle_point = (c+d)/2

  approximated_index_i = int(round(middle_point,0)) #for taking value from counted matrix
  approximated_index_j = int(round(middle_point - x_i + t_j)) #for taking value from counted matrix
  return h* ( a_t.compute(middle_point) * fi_u.compute( f[approximated_index_i][approximated_index_j])   )

In [ ]:
def integral_A_to_B(a,b,f, x_i, t_j):
  #define num of steps for calculating integral on segment
  num_of_steps = 10

  ret_value = 0.0
  h=(b-a)/num_of_steps

  for j in range(num_of_steps):
    ret_value+=integral_on_simple_segment(a+j*h, a+(j+1)*h, h, f, x_i, t_j)
  
  return ret_value


### *Iteration scheme implementation*

**set num of iterations**

In [ ]:
num_of_iterations = 100

**start calculations**

In [ ]:
#calculating U_(n+1) = f(U_n)
for steps in range(num_of_iterations):
  for i in range(0,(N_t) + 1):  # t defines rows
    for j in range(0, (N_x) + 1): # x defines colomns
      #x_i
      x_i=x_0+h_x*j
      
      #t_j 
      t_j = t_0 + h_t*i

      if (t_j <= x_i):
        matrix_cur[i][j] = alpha_x.compute(x_i - t_j) - integral_A_to_B(x_i - t_j, x_i,matrix_prev, x_i, t_j)
      
      else:
        matrix_cur[i][j] = kci_t.compute(t_j - x_i) - integral_A_to_B(0,x_i,matrix_prev, x_i, t_j)
      
  matrix_prev=deepcopy(matrix_cur)

print(matrix_cur)




[[ 2.00000000e+00  1.90000000e+00  1.80000000e+00  1.70000000e+00  1.60000000e+00  1.50000000e+00  1.40000000e+00  1.30000000e+00  1.20000000e+00  1.10000000e+00  1.00000000e+00]
 [ 1.00000000e-01  1.80000000e+00  1.70000000e+00  1.60000000e+00  1.50000000e+00  1.40000000e+00  1.49000000e+00  1.39000000e+00  1.29000000e+00  1.19000000e+00  1.09000000e+00]
 [ 2.00000000e-01 -1.00000000e-01  1.60000000e+00  1.50000000e+00  1.40000000e+00  1.30000000e+00  1.39000000e+00  1.48000000e+00  1.38000000e+00  1.28000000e+00  1.18000000e+00]
 [ 3.00000000e-01  5.55111512e-17 -3.00000000e-01  1.40000000e+00  1.30000000e+00  1.20000000e+00  1.27100000e+00  1.39900000e+00  1.47000000e+00  1.37000000e+00  1.27000000e+00]
 [ 4.00000000e-01  1.00000000e-01 -2.00000000e-01 -5.00000000e-01  1.20000000e+00  1.10000000e+00  1.15200000e+00  1.28000000e+00  1.33200000e+00  1.46000000e+00  1.36000000e+00]
 [ 5.00000000e-01  2.00000000e-01 -1.00000000e-01 -4.00000000e-01 -7.00000000e-01  1.00000000e+00  1.0900

TEST!!!

In [ ]:
#calculate integral on simple segment
def integral_on_simple_segment_test(c,d,h, f, x_i,t_j, i ,j):
  middle_point = (c+d)/2

  # approximated_index_i = int(round(middle_point,0)) #for taking value from counted matrix
  # approximated_index_j = int(round(middle_point - x_i + t_j)) #for taking value from counted matrix
  return h* ( a_t.compute(middle_point) * fi_u.compute( f[i][j])   )
  # return h * calculate_mean(f,c,d)

In [ ]:
def integral_A_to_B_test(a,b,f, x_i, t_j):
  #for x
  j_start = int(round( (x_i-t_j - x_0)/h_x, 0))
  j_finish = int (round( (x_i - x_0)/h_x, 0))

  #for t
  i_start = int(round( (0) , 0))
  i_finish = int(round ( (t_j - t_0)/h_t , 0))
  # i_finish = int(round ( (t_j + x_i - t_0)/h_t , 0))
  
  #define num of steps for calculating integral on segment
  num_of_steps = j_finish - j_start

  #difference in h_x and h_t step
  diff = int(round(h_x/h_t,0))
  

  ret_value = 0.0
  # h=(b-a)/num_of_steps

  for j in range(num_of_steps):
    ret_value+=integral_on_simple_segment_test(a+j*h_x, a+(j+1)*h_x, h_x, f, x_i, t_j, j_start+j, i_start+j*diff)
    
    

  return ret_value


In [ ]:
matrix_prev = np.zeros((N_x + 1,N_t + 1))
matrix_prev = deepcopy(matrix)

matrix_cur = np.zeros((N_x + 1,N_t + 1))
#calculating U_(n+1) = f(U_n)
for steps in range(num_of_iterations):
  for i in range(0,(N_t) + 1):  # t defines rows
    for j in range(0, (N_x) + 1): # x defines colomns
      #x_i
      x_i=x_0+h_x*j
      
      #t_j 
      t_j = t_0 + h_t*i

      if (t_j <= x_i):
        matrix_cur[i][j] = alpha_x.compute(x_i - t_j) - integral_A_to_B_test(x_i - t_j, x_i,matrix_prev, x_i, t_j)
      
      else:
        matrix_cur[i][j] = kci_t.compute(t_j - x_i) - integral_A_to_B_test(0,x_i,matrix_prev, x_i, t_j)
      
  matrix_prev=deepcopy(matrix_cur)

print(matrix_cur)


[[ 2.          1.9         1.8         1.7         1.6         1.5         1.4         1.3         1.2         1.1         1.        ]
 [-0.10085081  1.8         1.91008508  1.81284845  1.70696227  1.59184622  1.46800157  1.33711579  1.20183362  1.06524163  0.93025775]
 [-0.12848449 -0.29085081  1.62        1.93917016  1.8436969   1.73092454  1.59969243  1.45100315  1.28823159  1.11666725  0.94248326]
 [-0.06962269 -0.30848449 -0.48185932  1.458       1.98735609  1.89267383  1.77195643  1.62345711  1.44868474  1.25271854  1.04351921]
 [ 0.08153784 -0.23962269 -0.48976934 -0.67577634  1.3122      2.05493373  1.96008773  1.83029757  1.66321871  1.46087636  1.23008781]
 [ 0.31998426 -0.07846216 -0.41031892 -0.67413903 -0.87451195  1.18098     2.14238492  2.04642838  1.90635827  1.71921488  1.48755483]
 [ 0.62884206  0.16998426 -0.23764678 -0.58341137 -0.86340641 -1.08000532  1.062882    2.25038545  2.15236989  2.00072194  1.79184324]
 [ 0.98166375  0.48884206  0.0231841  -0.39761602 -0.76

# **#2nd Method**

## *Explicit computation scheme*

## ----------------------------------------

*Calculating integral on simple segment*

In [ ]:
#calculate integral on simple segment (for function a(s))
def integral_on_simple_segment_method_2(c,d,h, f):
  # c - start value
  # d - end value
  # h - step ( equals to: (d - c) )
  middle_point = (c+d)/2

  return h* f.compute(middle_point)

*Calculating integral on given segment from A to B*

In [ ]:
def integral_A_to_B_method_2(a,b,f):
  #define num of steps for calculating integral on segment
  num_of_steps = 10

  ret_value = 0.0
  h=(b-a)/num_of_steps

  for j in range(num_of_steps):
    ret_value+=integral_on_simple_segment_method_2(a+j*h, a+(j+1)*h, h, f)
  
  return ret_value




## ----------------------------------------

## *Code block for implementing inverse function for fi(U)*

*Setting grids*

x grid

In [ ]:
# x_grid range = x_grid_length   x_grid = [-1/2 * x_grid_length ; 1/2 * x_grid_length]
x_grid_range = 10

x_grid_length = x_grid_range * 2 #for minus values

x_grid_length_for_array_implementation = x_grid_length + 1
x_grid = np.zeros(x_grid_length_for_array_implementation)
for j in range(x_grid_length_for_array_implementation):

  x_grid[j] = j - (1/2) * x_grid_length

print (x_grid)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


y grid

In [ ]:
# y_grid range = y_grid_length   y_grid = [-1/2 * y_grid_length ; 1/2 * y_grid_length]
y_grid_range = 100

y_grid_length = y_grid_range * 2

y_grid_length_for_array_implementation = y_grid_length + 1
y_grid = np.zeros(y_grid_length_for_array_implementation)
for j in range(y_grid_length_for_array_implementation):

  y_grid[j] = j - (1/2) * y_grid_length

print (y_grid)

[-100.  -99.  -98.  -97.  -96.  -95.  -94.  -93.  -92.  -91.  -90.  -89.  -88.  -87.  -86.  -85.  -84.  -83.  -82.  -81.  -80.  -79.  -78.  -77.  -76.  -75.  -74.  -73.  -72.  -71.  -70.  -69.  -68.  -67.  -66.  -65.  -64.  -63.  -62.  -61.  -60.  -59.  -58.  -57.  -56.  -55.  -54.  -53.  -52.  -51.  -50.  -49.  -48.  -47.  -46.  -45.  -44.  -43.  -42.  -41.  -40.  -39.  -38.  -37.  -36.  -35.  -34.  -33.  -32.  -31.  -30.  -29.  -28.  -27.  -26.  -25.  -24.  -23.  -22.  -21.  -20.  -19.  -18.  -17.  -16.  -15.  -14.  -13.  -12.  -11.  -10.   -9.   -8.   -7.   -6.   -5.   -4.   -3.   -2.   -1.    0.    1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.   61.   62.   63.   64.   65.   6

Fill in the grid of function values fi_u (x)

In [ ]:
#structure for fi_u(x) values
from dataclasses import dataclass


class fi_u_struct:

    def __init__(self, f_value , arg_value):
      self.f_value = f_value
      self.arg_value = arg_value

    def get_f_value(self):
      return self.f_value

    def get_arg_value(self):
      return self.arg_value
    
    def __str__(self):
      return "[ "+str(self.f_value) + " || " + str(self.arg_value) + " ];"

In [ ]:
#uncounted values will be set as np.NaN

#fi_u(x) values will be strored as a structure = {grid_value ; x that gave that result}

init_array_struct = fi_u_struct(0.,0.)

fi_u_grid  = np.empty(shape=(x_grid_length_for_array_implementation,), dtype=object)

for j in range(x_grid_length_for_array_implementation):
  arg = x_grid[j]
  f_value = fi_u.compute(arg)

  fi_u_grid[j] = fi_u_struct(f_value , arg)

for j in range(x_grid_length_for_array_implementation):
  print (fi_u_grid[j])


Sorting fi_u grid by func values in ascending order

In [ ]:
list1 = fi_u_grid.tolist()
list1.sort(key = lambda x: x.get_f_value(), reverse=False)
# for j in range(x_grid_length_for_array_implementation):
#   print (list1[j])

fi_u_grid=np.array(list1)
for j in range(x_grid_length_for_array_implementation):
  print (fi_u_grid[j])

**Compute inverse function for fi(u)**

In [ ]:
def search_left_index_fi_u_grid(value):
  for i in range(len(fi_u_grid)):
    if (fi_u_grid[i].get_f_value() <= value):# [ * | | value | | | |]
      if ((i+1)<len(fi_u_grid)):# i not the right side of array
        if (fi_u_grid[i+1].get_f_value() < value):
          continue
        else:
          return i
      else:# i the right side of array --- BAD SITUTION - THROW EXCEPTION(need to compute wider grid_fi_u)
        raise ValueError('Need to compute wider grid_fi_u')
    else:# i the left side of array bigger than value --- BAD SITUTION - THROW EXCEPTION(need to compute wider grid_fi_u)
      raise ValueError('Need to compute wider grid_fi_u LEFT SIDE')


In [ ]:
def compute_weight(value, our_point, whole_dist_between_border_points):
  return ( (abs(value - our_point)) / whole_dist_between_border_points)

In [ ]:
def inverse_fi(y_0):
  left_index = search_left_index_fi_u_grid(y_0)

  #search left and right side distance ftom y_0   ---> this will form an impact that left and right points enter
  left_point_value = fi_u_grid[left_index].get_f_value()
  right_point_value = fi_u_grid[left_index + 1].get_f_value()

  whole_dist_between_border_points = abs(right_point_value - left_point_value)

  #compute weights
  left_side_weight = compute_weight(y_0,left_point_value,whole_dist_between_border_points)

  right_side_weight = compute_weight(y_0,right_point_value,whole_dist_between_border_points)

  #compute return value
  arg1 = fi_u_grid[left_index].get_arg_value()
  weight_arg1 = (1 - left_side_weight)

  arg2 = fi_u_grid[left_index + 1].get_arg_value()
  weight_arg2 = (1 - right_side_weight)

  return weight_arg1 * arg1   +  weight_arg2 * arg2





### ***Calculating U(x , t) values on the grid using method # 2***

In [35]:
matrix_method_3 = np.zeros((N_x + 1,N_t + 1))

In [ ]:
# First row filled with alpha(x_j)
for j in range(0, N_x+1):
  matrix_method_3[0][j] = alpha_x.compute(x_0 + h_x*j)

# First colomn filled with kci(t_i)
for i in range(0, N_t+1):
  matrix_method_3[i][0] = kci_t.compute(t_0 + h_t*i)

print(matrix_method_3)

*calculating entry point for inverse fi(u) function*

In [38]:
def calculate_point_1(x_j,t_i):#for situation 0 <= t <= x <= L
  fi_calculated_from_alpha = fi_u.compute(alpha_x.compute(x_j - t_i))
  
  calculated_integral = integral_A_to_B_method_2(x_j - t_i, x_j, a_t)

  return fi_calculated_from_alpha * math.exp( (-1) * calculated_integral )

In [39]:
def calculate_point_2(x_j,t_i):#for situation 0 <= x <= t <= T
  fi_calculated_from_kci = fi_u.compute( kci_t.compute(t_i - x_j) )
  
  calculated_integral = integral_A_to_B_method_2( 0, x_j, a_t )

  return fi_calculated_from_kci * math.exp( (-1) * calculated_integral )

*Processing matrix*

In [40]:
for i in range(1, (N_t) + 1):   # t defines rows
  for j in range(1, (N_x) + 1):     # x defines colomns

    x_j = x_0 + j * h_x

    t_i = t_0 + i * h_t

    if (t_i <= x_j):#for situation 0 <= t <= x <= L
      y_0 = calculate_point_1(x_j,t_i)
      matrix[i][j] = round(inverse_fi(y_0),3)
    
    else:#for situation 0 <= x <= t <= T
      y_0 = calculate_point_2(x_j,t_i)
      matrix[i][j] = round(inverse_fi(y_0),3)

print(matrix)

[[0.    1.9   1.8   1.7   1.6   1.5   1.4   1.3   1.2   1.1   1.   ]
 [0.1   1.81  1.719 1.629 1.538 1.448 1.357 1.267 1.176 1.086 0.995]
 [0.2   0.09  1.637 1.556 1.474 1.392 1.31  1.228 1.146 1.064 0.982]
 [0.3   0.181 0.082 1.482 1.408 1.333 1.259 1.185 1.111 1.037 0.963]
 [0.4   0.271 0.164 0.074 1.341 1.274 1.207 1.14  1.073 1.005 0.938]
 [0.5   0.362 0.246 0.148 0.067 1.213 1.152 1.092 1.031 0.97  0.91 ]
 [0.6   0.452 0.327 0.222 0.134 0.061 1.098 1.043 0.988 0.933 0.878]
 [0.7   0.543 0.409 0.296 0.201 0.121 0.055 0.993 0.944 0.894 0.844]
 [0.8   0.633 0.491 0.37  0.268 0.182 0.11  0.05  0.899 0.854 0.809]
 [0.9   0.724 0.573 0.444 0.335 0.243 0.165 0.099 0.045 0.813 0.772]
 [1.    0.814 0.655 0.519 0.402 0.303 0.22  0.149 0.09  0.041 0.736]]
